---
include:
 - board: seeeduino_xiao_ble
   shield: roBa_dongle prospector_adapter
   snippet: studio-rpc-usb-uart
 - board: seeeduino_xiao_ble
   shield: roBa_R rgbled_adapter
 - board: seeeduino_xiao_ble
   shield: roBa_L rgbled_adapter
 - board: seeeduino_xiao_ble
   shield: settings_reset
