---
include:
 - board: seeeduino_xiao_ble
   shield: roBa_R rgbled_adapter
   snippet: zmk-usb-logging
 - board: seeeduino_xiao_ble
   shield: roBa_L rgbled_adapter
   snippet: zmk-usb-logging
 - board: seeeduino_xiao_ble
   shield: settings_reset
