---
include:
 - board: xiao_ble//zmk
   shield: roBa_R rgbled_adapter
   snippet: studio-rpc-usb-uart
 - board: xiao_ble//zmk
   shield: roBa_L rgbled_adapter
 - board: xiao_ble//zmk
   shield: settings_reset
