name: Build with nix setup
on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - config/**
  #     - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@9ebfa3ed81027d7907a8629f2085ae72e4c03b80 # v11.0.2
    with:
      # Optionally choose the toolchain to use: Zephyr SDK (default) or GNU Arm
      # Embedded ('gnuarmemb'). The latter results in slightly faster builds.
      toolchain: zephyr
