name: Build with nix setup
on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - config/**
  #     - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@21d0254c00fa8e85b20089df82dc5e96d5029bd4 # v11.0.5
    with:
      # Optionally choose the toolchain to use: Zephyr SDK (default) or GNU Arm
      # Embedded ('gnuarmemb'). The latter results in slightly faster builds.
      toolchain: zephyr
