name: Build
on:
  workflow_dispatch:
  pull_request:
  # push:
  #   paths:
  #     - config/**
  #     - build.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@cb615aee9a7c427e251f2ab62080c1a44a165da9 # v0.3.0
