name: Build
on:
  workflow_dispatch:
  pull_request:
  # push:
  #   paths:
  #     - config/**
  #     - build.yaml

jobs:
  build:
    # uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    uses: petejohanson/zmk/.github/workflows/build-user-config.yml@core/move-to-zephyr-4-1
